# Generated by Django 2.1.2 on 2019-07-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataQusetion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col_name', models.CharField(max_length=255)),
                ('desc_str', models.CharField(max_length=255)),
            ],
            options={
                'managed': False,
                'db_table': 'data_qusetion',
            },
        ),
        migrations.CreateModel(
            name='DataTrans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_str', models.CharField(max_length=255)),
            ],
            options={
                'managed': False,
                'db_table': 'data_trans',
            },
        ),
        migrations.CreateModel(
            name='DeletePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_str', models.CharField(max_length=255)),
            ],
            options={
                'managed': False,
                'db_table': 'delete_point',
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'django_migrations',
            },
        ),
        migrations.CreateModel(
            name='DpiaInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_email_list', models.CharField(max_length=255)),
                ('pro_name', models.IntegerField(blank=True, null=True)),
                ('pro_desc', models.CharField(max_length=255)),
                ('user_country', models.CharField(max_length=255)),
                ('data_country', models.CharField(max_length=255)),
                ('pro_pri_leader', models.CharField(blank=True, max_length=255, null=True)),
                ('pro_pri_name', models.CharField(blank=True, max_length=255, null=True)),
                ('net_id_account', models.IntegerField(blank=True, null=True)),
                ('net_id_api', models.IntegerField(blank=True, null=True)),
                ('net_id_password', models.IntegerField(blank=True, null=True)),
                ('asset_password', models.IntegerField(blank=True, null=True)),
                ('basis_name', models.IntegerField(blank=True, null=True)),
                ('basis_mobilephone', models.IntegerField(blank=True, null=True)),
                ('basis_telephone', models.IntegerField(blank=True, null=True)),
                ('basis_address', models.IntegerField(blank=True, null=True)),
                ('basis_email', models.IntegerField(blank=True, null=True)),
                ('position_gps', models.IntegerField(blank=True, null=True)),
                ('personal_id', models.IntegerField(blank=True, null=True)),
                ('biology_face', models.IntegerField(blank=True, null=True)),
                ('biology_voice', models.IntegerField(blank=True, null=True)),
                ('biology_finger', models.IntegerField(blank=True, null=True)),
                ('biology_portrait', models.IntegerField(blank=True, null=True)),
                ('biology_other', models.IntegerField(blank=True, null=True)),
                ('device_mobile', models.IntegerField(blank=True, null=True)),
                ('device_imei', models.IntegerField(blank=True, null=True)),
                ('device_apps', models.IntegerField(blank=True, null=True)),
                ('device_security', models.IntegerField(blank=True, null=True)),
                ('device_pkgs', models.IntegerField(blank=True, null=True)),
                ('checklist_dpia_check', models.IntegerField()),
                ('checklist_db_manage', models.IntegerField()),
                ('checklist_privacy_policy', models.IntegerField()),
                ('checklist_user_allow', models.IntegerField()),
                ('checklist_feedback', models.IntegerField()),
                ('checklist_dataleak', models.IntegerField(blank=True, null=True)),
                ('checklist_backinfo', models.CharField(blank=True, max_length=511, null=True)),
                ('checklist_dataflow', models.CharField(blank=True, max_length=511, null=True)),
                ('checklist_dataleak_path', models.CharField(blank=True, max_length=255, null=True)),
                ('checklist_dataleak_name', models.CharField(blank=True, max_length=255, null=True)),
                ('add_time', models.DateTimeField(auto_now=True)),
                ('checklist_api', models.IntegerField()),
                ('checklist_api_name', models.CharField(blank=True, max_length=255, null=True)),
                ('data_trans', models.CharField(max_length=255)),
                ('deal_nation', models.IntegerField(blank=True, null=True)),
                ('deal_politic', models.IntegerField(blank=True, null=True)),
                ('deal_religion', models.IntegerField(blank=True, null=True)),
                ('deal_member', models.IntegerField(blank=True, null=True)),
                ('deal_biology', models.IntegerField(blank=True, null=True)),
                ('deal_health', models.IntegerField(blank=True, null=True)),
                ('deal_sex', models.IntegerField(blank=True, null=True)),
                ('showid', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'dpia_info',
            },
        ),
        migrations.CreateModel(
            name='GetNess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_str', models.CharField(max_length=255)),
            ],
            options={
                'managed': False,
                'db_table': 'get_ness',
            },
        ),
        migrations.CreateModel(
            name='GetSrc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_str', models.CharField(max_length=255)),
            ],
            options={
                'managed': False,
                'db_table': 'get_src',
            },
        ),
        migrations.CreateModel(
            name='HighRisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_str', models.CharField(max_length=255)),
            ],
            options={
                'managed': False,
                'db_table': 'high_risk',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('depart', models.CharField(blank=True, max_length=255, null=True)),
                ('leader', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'manager',
            },
        ),
        migrations.CreateModel(
            name='PrivacyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy_type_id', models.IntegerField()),
                ('dpia_id', models.IntegerField(blank=True, null=True)),
                ('privacy_backinfo', models.CharField(blank=True, max_length=511, null=True)),
                ('get_ness', models.IntegerField()),
                ('get_src', models.CharField(max_length=63)),
                ('use_show', models.IntegerField()),
                ('use_dp', models.IntegerField()),
                ('use_log', models.IntegerField()),
                ('trans_out', models.IntegerField()),
                ('trans_in', models.IntegerField()),
                ('storage_point', models.IntegerField()),
                ('storage_allow', models.IntegerField()),
                ('storage_encryp', models.IntegerField()),
                ('server_log', models.IntegerField()),
                ('delete_point', models.IntegerField()),
                ('privacy_infoc', models.CharField(max_length=511)),
            ],
            options={
                'managed': False,
                'db_table': 'privacy_info',
            },
        ),
        migrations.CreateModel(
            name='PrivacyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_str', models.CharField(max_length=255)),
                ('col_name', models.CharField(max_length=255)),
                ('get_ness', models.IntegerField()),
                ('get_src', models.IntegerField()),
                ('use_show', models.IntegerField()),
                ('use_dp', models.IntegerField()),
                ('use_log', models.IntegerField()),
                ('trans_in', models.IntegerField()),
                ('trans_out', models.IntegerField()),
                ('storage_allow', models.IntegerField()),
                ('storage_encryp', models.IntegerField()),
                ('delete_point', models.IntegerField()),
                ('storage_point', models.IntegerField()),
                ('server_log', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'privacy_type',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=255)),
            ],
            options={
                'managed': False,
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ServerLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_str', models.CharField(max_length=255)),
            ],
            options={
                'managed': False,
                'db_table': 'server_log',
            },
        ),
        migrations.CreateModel(
            name='StorageAllow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_str', models.CharField(max_length=255)),
            ],
            options={
                'managed': False,
                'db_table': 'storage_allow',
            },
        ),
        migrations.CreateModel(
            name='StorageEncryp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_str', models.CharField(max_length=255)),
            ],
            options={
                'managed': False,
                'db_table': 'storage_encryp',
            },
        ),
        migrations.CreateModel(
            name='StoragePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_str', models.CharField(max_length=255)),
            ],
            options={
                'managed': False,
                'db_table': 'storage_point',
            },
        ),
        migrations.CreateModel(
            name='TransIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_str', models.CharField(max_length=255)),
            ],
            options={
                'managed': False,
                'db_table': 'trans_in',
            },
        ),
        migrations.CreateModel(
            name='TransOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_str', models.CharField(max_length=255)),
            ],
            options={
                'managed': False,
                'db_table': 'trans_out',
            },
        ),
        migrations.CreateModel(
            name='UseDp',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('desc_str', models.CharField(max_length=255)),
            ],
            options={
                'managed': False,
                'db_table': 'use_dp',
            },
        ),
        migrations.CreateModel(
            name='UseLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_str', models.CharField(max_length=255)),
            ],
            options={
                'managed': False,
                'db_table': 'use_log',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.CharField(blank=True, max_length=32, null=True)),
                ('password', models.CharField(blank=True, max_length=32, null=True)),
                ('nickname', models.CharField(blank=True, max_length=32, null=True)),
                ('role', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_str', models.CharField(max_length=255)),
            ],
            options={
                'managed': False,
                'db_table': 'user_country',
            },
        ),
        migrations.CreateModel(
            name='UseShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_str', models.CharField(max_length=255)),
            ],
            options={
                'managed': False,
                'db_table': 'use_show',
            },
        ),
    ]
